name: Run E2E Tests

permissions:
  checks: write
  pull-requests: write
  id-token: write

on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-e2e-tests
